version: '3'

networks:
  monitoring:
    driver: bridge

services:
  security-api:
    container_name: "security-api"
    build: 
      context: ..
      dockerfile: ./Security-API/Dockerfile  
    environment:
      DBCONNECTION: "host=security-postgres:5432; database=security_db; user id=admin; password=password"
    ports:
      - "8080:8080"
    networks:
      - monitoring

  security-web:
    container_name: "security-web"
    build: 
      context: ..
      dockerfile: ./Security-Web/Dockerfile
    environment:
        APIBASEURL: "http://localhost:1365"
    ports:
      - "80:80"
    networks:
      - monitoring

  security-postgres:
    container_name: "security-postgres"
    image: postgres:latest
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./Database/securityappcreationscript.sql:/docker-entrypoint-initdb.d/securityappcreationscript.sql
    ports:
      - "5432:5432"
    networks:
      - monitoring