#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Security-Web/Security-Web.csproj", "Security-Web/"]
RUN pwd
RUN dotnet clean "./Security-Web/./Security-Web.csproj"
RUN dotnet restore "./Security-Web/./Security-Web.csproj"
COPY . .
WORKDIR "/src/Security-Web"
RUN dotnet build "./Security-Web.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Security-Web.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM nginx:alpine
WORKDIR /user/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY Security-Web/nginx.conf /etc/nginx/nginx.conf
